### Adapted from Amazon SageMaker Examples: Advanced Functionality, AutoGluon Tabular Containers
###https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/autogluon-tabular-containers/config/config-med.yaml

ag_predictor_args:
  eval_metric: roc_auc #other metric
  label: target #label for the target column
  problem_type: binary

ag_fit_args:
  hyperparameters:
#     GBM:
#       num_boost_round: 20
#     NN:
#       num_epochs: 2
  presets: "best_quality"
  num_bag_folds: 5
  num_bag_sets: 1
  num_stack_levels: 0

output_prediction_format: csv  # predictions output format: csv or parquet
feature_importance: true       # calculate and save feature importance if true
leaderboard: true              # save leaderboard output if true